### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by urstrulykkr** [urstrulykkr/Robo-Search#4]

**Comment by promise** [comment]
I can help you with this, if you tell me a bit more about your project. Currently there's only a README, and I can't help much unless more context is added.

**Comment by Dilruwan95** [comment]
I can help you with this, if you tell me a bit more about your project.

**Comment by urstrulykkr** [comment]
Hi @Dilruwan95  and @gleeny ,
Sorry for the late update this isue is no longer a valid issue for Hacktoberfest. I will close this issue.
Sorry for the disappointment :(
